# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2f2612af209a0dcddd83dedf02a4ff92fa816533c62648f0875dcf7e04fe29eb495252b7d5fdba3600ba4c88b9bf65cc62c26a2e5dc934c9886c16a12d4c243

test:
  secret_key_base: 8f8623f29656275ba9e81248d4da847b49064496e50ce81e443f9980b7b03b91bbf7409c1dbaf3addd7b12f586a8ac9beb3c969dc4388334347974fa5785c2b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
